### ISSUE TITLE
How to change appearance animation with .attach()

### ISSUE THREAD

**Issue by Sabellus** [OfTheWolf/UBottomSheet#16] opened 2020-03-04 12:45 UTC
I want to .attach bottomshett to appear at the bottom, and not at the top left!
thanks for the help @OfTheWolf

**Comment by OfTheWolf** [comment] 2020-03-05 20:35
I didn't understand what did you mean with top left. 

You can animate child view controllers by modifiying the code in [ub_add](https://github.com/OfTheWolf/UBottomSheet/blob/master/UBottomSheet/Classes/Extensions.swift#L12) and [ub_remove](https://github.com/OfTheWolf/UBottomSheet/blob/master/UBottomSheet/Classes/Extensions.swift#L24) as you wish.

For example:
```
UIView.transition(with: self.view, duration: 0.5, options: .transitionFlipFromBottom, animations: { _ in
    self.view.addSubview(v)
}, completion: nil) 
```

@Sabellus

**Comment by Sabellus** [comment] 2020-03-05 20:55
that’s what I mean, appears from the top left
![screen](https://user-images.githubusercontent.com/24656120/76024751-75b2e400-5f4d-11ea-83d8-08f2b5275cb6.png)
@OfTheWolf

**Comment by OfTheWolf** [comment] 2020-03-05 21:01
It looks strange. It is not the intended behaviour. Normally it should show up from bottom. Can you share minimal code to replicate it? @Sabellus

**Comment by Sabellus** [comment] 2020-03-05 21:55
![image](https://user-images.githubusercontent.com/24656120/76028996-7cddf000-5f55-11ea-8d11-43a0037d376c.png)

Here in the example I added the attach button @OfTheWolf 
What am i doing wrong?

```
let vc = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "MapsDemoBottomSheetController") as! MapsDemoBottomSheetController
    @IBAction func atAction(_ sender: Any) {
        vc.attach(to: self)
    }
    override func viewDidLoad() {
        super.viewDidLoad()
    }
```

**Comment by OfTheWolf** [comment] 2020-03-05 23:22
@Sabellus I tried with ipad air and iphone 11 pro max - 13.3 too. still couldn't reproduce the issue. attach simply add child vc to the parent (self) and add the autolayout constraints to the edges. Maybe you can check if your parent vc is correct and has the correct frame before attach the bottom sheet.

**Comment by OfTheWolf** [comment] 2020-05-01 15:07
I am closing the issue as i can't reproduce and you haven't responded yet. If you experience it again you can create a new issue.

**Closed as completed by OfTheWolf** 2020-05-01 15:07 UTC
